#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

# branches to build
branches:
  # whitelist
  only:
    - master

# Maximum number of concurrent jobs for the project
max_jobs: 1

#shallow_clone: true

image: Visual Studio 2019

# scripts that are called at very beginning, before repo cloning
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch
  - CALL c:\projects\sonnet\appveyor-install.bat

# enable patching of AssemblyInfo.* files
#assembly_info:
#  patch: true
#  file: AssemblyInfo.*
#  assembly_version: "2.2.{build}"
#  assembly_file_version: "{version}"
#  assembly_informational_version: "{version}"

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
# to add several platforms to build matrix:
platform:
  - x86
#  - x64

# build Configuration, i.e. Debug, Release, etc.
configuration:
#  - Debug
  - Release

build:
#  parallel: true                  # enable MSBuild parallel builds
  project: c:\projects\sonnet\MSVisualStudio\v16\Sonnet.sln # path to Visual Studio solution or project