---
name: Windows build and test
on:
  push:
    branches:
      - 'master'
      - 'stable/*'
  pull_request:
    branches:
      - '**'
  release:
    types:
      - created

jobs:
  build_and_test:
    name: Build and Test
    runs-on: windows-2022
    steps:
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6

      - name: Checkout Sonnet source
        uses: actions/checkout@v2
        with:
          path: Sonnet

      - name: Checkout dependenies sources
        run: |
          git clone --depth 1 https://github.com/coin-or-tools/BuildTools.git -b master 
          git clone --depth 1 https://github.com/coin-or/Cbc.git -b master
          git clone --depth 1 https://github.com/coin-or/Clp.git -b master
          git clone --depth 1 https://github.com/coin-or/Cgl.git -b master
          git clone --depth 1 https://github.com/coin-or/CoinUtils.git -b master
          git clone --depth 1 https://github.com/coin-or/Osi.git -b master
          git clone --depth 1 https://github.com/coin-or-tools/Data-Sample -b master
          git clone --depth 1 https://github.com/coin-or-tools/Data-miplib3 -b master
          7z x -bso0 -oData-miplib3 Data-miplib3\*.gz

      - name: Prepare for build
        run: nuget restore Sonnet\MSVisualStudio\v17\Sonnet.sln

      - name: Build
        run: msbuild Sonnet\MSVisualStudio\v17\Sonnet.sln -p:Configuration=Release -p:Platform=x64 -m

      - name: Run tests for net4 framework
        shell: cmd
        run: |
          cd Sonnet\MSVisualStudio\v17\SonnetTestNET4\bin\x64\Release\
          erase expect-feasible.mps
          vstest.console SonnetTest.exe 
  
      - name: Run tests for net6.0
        if: always()
        shell: cmd
        run: |
          cd Sonnet\MSVisualStudio\v17\SonnetTest\bin\x64\Release\net6.0\
          dotnet test SonnetTest.exe --logger "trx;LogFileName=test-net60-results.trx"

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: DotNET Tests
          working-directory: Sonnet
          path: "**/test-net60-results.trx"                            
          reporter: dotnet-trx
          fail-on-error: true
